name: Test and Deploy
concurrency:
  group: main
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    name: Run Test
    runs-on: ubuntu-latest
    container:
      image: bwainwrighttnm/tnm-deps:main

    steps:
      - name: List Dir
        shell: 'bash'
        run: ls
      - uses: actions/checkout@v3

      - name: Configure node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List Dir
        shell: 'bash'
        run: ls

      - name: Install Dependencies
        shell: 'bash'
        run: yarn install --frozen-lockfile
