name: Test and Deploy
concurrency:
  group: main
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  bake-dependencies:
    name: Bake Latest Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: List Dir
        shell: 'bash'
        run: ls
      - uses: actions/checkout@v3

      - name: Configure node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List Dir
        shell: 'bash'
        run: ls

      - name: Install Dependencies
        shell: 'bash'
        run: yarn install --frozen-lockfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: bwainwrighttnm/tnm-deps

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            workspace_path={{ env.GITHUB_WORKSPACE }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-tests:
    name: Run Test
    runs-on: ubuntu-latest
    container:
      image: bwainwrighttnm/tnm-deps:main

    steps:
      - name: List Dir
        shell: 'bash'
        run: ls
      - uses: actions/checkout@v3

      - name: Configure node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List Dir
        shell: 'bash'
        run: ls

      - name: Install Dependencies
        shell: 'bash'
        run: yarn install --frozen-lockfile
