name: Test and Deploy
concurrency:
  group: main
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - name: Configure node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        shell: 'bash'
        run: yarn install --frozen-lockfile

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3
